-- 보호소에 들어온 동물 리스트 ANIMAL_INS
-- 보호소에서 입양보낸 동물 리스트 ANIMAL_OUTS
-- 들어올때와 나갈때 중성화 여부가 다른 동물 
-- >>> 
SELECT INS.ANIMAL_ID,INS.ANIMAL_TYPE,INS.NAME
FROM ANIMAL_INS INS LEFT OUTER JOIN ANIMAL_OUTS OUTS
    on INS.ANIMAL_ID=OUTS.ANIMAL_ID
WHERE OUTS.SEX_UPON_OUTCOME != INS.SEX_UPON_INTAKE
ORDER BY INS.ANIMAL_ID ASC
