-- 보호소에 들어온 동물 리스트 ANIMAL_INS
-- 보호소에서 입양보낸 동물 리스트 ANIMAL_OUTS
-- 조건1) 입양을 간 동물 중 
-- ISNOTNULL 을 두 테이블에 적용
-- 조건2) 가장 오랜기간 보호한 동물 두마리
-- DATETIME out에서 in 빼서 가장 큰 숫자 정렬 LIMIT 2

-- 1 (OUT 테이블에서 아이디와 이름 조회)
SELECT OUTS.ANIMAL_ID,OUTS.NAME
FROM ANIMAL_INS INS LEFT OUTER JOIN ANIMAL_OUTS OUTS
    on INS.ANIMAL_ID=OUTS.ANIMAL_ID
ORDER BY OUTS.DATETIME - INS.DATETIME DESC
LIMIT 2

-- 2 (INS 테이블에서 아이디와 이름 조회))
SELECT INS.ANIMAL_ID,INS.NAME
FROM ANIMAL_INS INS LEFT OUTER JOIN ANIMAL_OUTS OUTS
    on INS.ANIMAL_ID=OUTS.ANIMAL_ID
ORDER BY OUTS.DATETIME - INS.DATETIME DESC
LIMIT 2