-- 시간별 보호소 입양 카운트
--  몇시 대에 가장 입양이 활발한지 시간대별 입양 건수 조회하기 
-- COUNT, GROUPBY
-- COUNT(DATETIME)
-- WHERE DATETIME %h = "(9-19)""
-- GROUP BY DATETIME()
SELECT HOUR(DATETIME) as HOUR, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) between 0 and 24
GROUP BY HOUR(DATETIME)
ORDER BY 1;
-- 0시부터 24시 사이의 조회가 되지 않음 
-- GROUP BY에 조건을 걸기 위해서 Having을 함께 사용
SELECT HOUR(DATETIME) as HOUR, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) between 0 and 24
GROUP BY HOUR(DATETIME)
HAVING MAX(CASE WHEN HOUR(DATETIME) = 'null' then 1 else 0 end) = 0
ORDER BY 1;